language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly



matrix:
    allow_failures:
        - php: '7.0'
        - php: '7.1'
        - php: hhvm
        - php: nightly



before_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - composer install


script: 
    - phpunit --bootstrap test/config.php --coverage-clover=coverage.clover test



after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
